# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZJ3Ny7bvDmStllUPf4ogzGm_yE-ZlGt
"""

msh ="jaipur"
msh[1:6:2]

range(1,7,3)

msg ="hey tushar"
msg[-1:-3:-1]

#List data type
mylist=[10,2,3,'abc']
print(mylist)
print(type(mylist))

mylist[-1]

mylist[0] =500
mylist[0:2]

mylist[0:2] =["a","b"]

mylist[0:2]

mylist.append(19)

print(mylist)

mylist.extend([10,12,15])
mylist

mylist.pop()
mylist
x=mylist.pop()
print(x)

for i in[10,12,13,14,'abc']:

  print(i)

mylist =[10,12,43,54,23,"sedfs"]
len(mylist)

mylist =[10,12,43,54,23,"sedfs"]
mylist[5]
for index in range(0,6):
  print(index, mylist[index])

#find those number which is even in a list
mylist =[1,2,3,4,5,6,7,8,946,3232]
for index in range(0,len(mylist)):
  if(mylist[index] % 2 == 0):
    print(mylist[index])

mylist=[1,2,3,465,"ab","d"]
for index in range(0,len(mylist)):
    if(type(mylist[index]))=="int":
        print(mylist[index]*mylist[index])

for i in ["a",'b',"c",10,11]:
  if(type(i)==int):
    print(i*i)

x =11
mylist=[10,12,223,101,11]
if x in mylist:
  print("yes")
else:
  print("no")

#for cheching duplication
mylist=[10,12,223,101,11,90]
x=0
for i in range(0 ,len(mylist)):
  for j in range(i+1,len(mylist)):
    print(mylist[i] ,mylist[j])
    x+=1
if(x==0):
  print("duplication in list")

else:
    print("no duplication")

mylist=[10,12,223,101,11,90,10,10]
duplicate =[]

x=0
for i in range(0 ,len(mylist)):
  for j in range(i+1,len(mylist)):
    if(mylist[i]==mylist[j]):
      duplicate.append(mylist[i])
print(duplicate)

mylist=[10,12,223,101,11,90,10,10]